In [ ]:
The purpose of the given project is an analysis of the market data and the elaboration of a general overview of the German 
rental real estate market. We will analyze parsed data about the rental real estate offers to determine the price range, 
the factors of influence, and the locations that may significantly influence the rental price.

So the data set is huge. It is a bit difficult to use R to analyse large data sets. So I used jupyter to analyse the data
and reduced it to the exact information I need. I am more interested in data sets related to Munchen since this is where I live.

The data sets obtained after cleaning were then converted to a csv format and then opened in R.

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing
import matplotlib.pyplot as plt # dataviz
import seaborn as sns # dataviz

In [2]:
df = pd.read_csv("C:/Users/admin/Desktop/First_github_project/second_project/immo_data.csv")

In [3]:
%matplotlib inline

In [4]:
df = df.drop(['telekomHybridUploadSpeed', 'noParkSpaces', 'houseNumber', \
              'heatingCosts', 'energyEfficiencyClass', 'lastRefurbish', \
              'telekomTvOffer', 'telekomUploadSpeed', 'streetPlain', \
              'numberOfFloors', 'floor', 'firingTypes', 'serviceCharge', \
              'description', 'facilities', 'scoutId', 'pricetrend',
              'baseRentRange', 'noRoomsRange', 'livingSpaceRange', \
              'yearConstructedRange'], axis=1) #drop columns that aren't needed

In [5]:
df = df[df.regio1=='Bayern'] #pick out only Bayern

In [6]:
df

,regio1,heatingType,newlyConst,balcony,picturecount,totalRent,yearConstructed,hasKitchen,geo_bln,cellar,...,typeOfFlat,geo_plz,noRooms,thermalChar,garden,regio2,regio3,electricityBasePrice,electricityKwhPrice,date
23,Bayern,central_heating,False,False,18,2030.0,1871.0,True,Bayern,True,...,apartment,80331,2.0,48.4,False,München,Altstadt,NaN,NaN,Oct19
28,Bayern,NaN,False,True,25,2400.0,1956.0,False,Bayern,False,...,NaN,80804,3.0,210.6,False,München,Schwabing_West,NaN,NaN,May19
30,Bayern,floor_heating,False,True,15,970.0,1974.0,True,Bayern,True,...,ground_floor,94036,2.0,NaN,False,Passau,Haidenhof_Süd,90.76,0.1985,Sep18
32,Bayern,NaN,False,True,29,2780.0,2016.0,False,Bayern,False,...,NaN,80809,3.0,44.8,False,München,Milbertshofen,NaN,NaN,Feb20
49,Bayern,NaN,False,False,11,NaN,2007.0,False,Bayern,False,...,NaN,63743,3.0,NaN,False,Aschaffenburg,Obernauer_Kolonie,NaN,NaN,May19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268774,Bayern,central_heating,True,True,20,2106.0,2020.0,True,Bayern,True,...,terraced_flat,85764,4.0,NaN,True,München_Kreis,Oberschleißheim,NaN,NaN,Feb20
268792,Bayern,floor_heating,True,True,9,1375.0,2018.0,True,Bayern,True,...,roof_storey,91560,3.0,NaN,False,Ansbach_Kreis,Heilsbronn,NaN,NaN,Oct19
268818,Bayern,central_heating,False,True,9,1792.0,NaN,False,Bayern,True,...,NaN,81677,3.0,175.8,False,München,Bogenhausen,NaN,NaN,May19
268839,Bayern,district_heating,False,True,15,1980.0,1900.0,True,Bayern,False,...,ground_floor,80799,2.0,NaN,False,München,Maxvorstadt,90.76,0.1985,Sep18
268845,Bayern,heat_pump,False,True,0,910.0,2016.0,False,Bayern,True,...,roof_storey,82390,3.0,NaN,False,Weilheim_Schongau_Kreis,Eberfing,NaN,NaN,Feb20

In [7]:
df = df[df.regio2=='München'] #pick out munchen

In [8]:
df

,regio1,heatingType,newlyConst,balcony,picturecount,totalRent,yearConstructed,hasKitchen,geo_bln,cellar,...,typeOfFlat,geo_plz,noRooms,thermalChar,garden,regio2,regio3,electricityBasePrice,electricityKwhPrice,date
23,Bayern,central_heating,False,False,18,2030.00,1871.0,True,Bayern,True,...,apartment,80331,2.0,48.4,False,München,Altstadt,NaN,NaN,Oct19
28,Bayern,NaN,False,True,25,2400.00,1956.0,False,Bayern,False,...,NaN,80804,3.0,210.6,False,München,Schwabing_West,NaN,NaN,May19
32,Bayern,NaN,False,True,29,2780.00,2016.0,False,Bayern,False,...,NaN,80809,3.0,44.8,False,München,Milbertshofen,NaN,NaN,Feb20
118,Bayern,NaN,True,True,14,1390.00,2018.0,False,Bayern,False,...,NaN,80807,1.0,81.0,False,München,Schwabing,NaN,NaN,May19
161,Bayern,district_heating,False,True,16,NaN,1959.0,True,Bayern,True,...,apartment,80469,2.0,76.7,True,München,Ludwigsvorstadt_Isarvorstadt,NaN,NaN,Oct19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268688,Bayern,oil_heating,False,True,24,2240.00,NaN,True,Bayern,True,...,ground_floor,81247,3.0,118.0,True,München,Obermenzing,NaN,NaN,Feb20
268712,Bayern,district_heating,False,True,11,1810.17,1980.0,False,Bayern,True,...,terraced_flat,81669,3.0,125.5,True,München,Ramersdorf,NaN,NaN,Oct19
268752,Bayern,central_heating,False,True,32,1290.00,1985.0,True,Bayern,True,...,apartment,80807,1.0,167.1,False,München,Milbertshofen,NaN,NaN,May19
268818,Bayern,central_heating,False,True,9,1792.00,NaN,False,Bayern,True,...,NaN,81677,3.0,175.8,False,München,Bogenhausen,NaN,NaN,May19
268839,Bayern,district_heating,False,True,15,1980.00,1900.0,True,Bayern,False,...,ground_floor,80799,2.0,NaN,False,München,Maxvorstadt,90.76,0.1985,Sep18

In [9]:
df = df.drop(['regio3', 'electricityBasePrice', 'electricityKwhPrice'], axis=1)

In [10]:
df

,regio1,heatingType,newlyConst,balcony,picturecount,totalRent,yearConstructed,hasKitchen,geo_bln,cellar,...,petsAllowed,street,lift,typeOfFlat,geo_plz,noRooms,thermalChar,garden,regio2,date
23,Bayern,central_heating,False,False,18,2030.00,1871.0,True,Bayern,True,...,no,no_information,False,apartment,80331,2.0,48.4,False,München,Oct19
28,Bayern,NaN,False,True,25,2400.00,1956.0,False,Bayern,False,...,NaN,Burgunderstra&szlig;e,True,NaN,80804,3.0,210.6,False,München,May19
32,Bayern,NaN,False,True,29,2780.00,2016.0,False,Bayern,False,...,NaN,Am Oberwiesenfeld,True,NaN,80809,3.0,44.8,False,München,Feb20
118,Bayern,NaN,True,True,14,1390.00,2018.0,False,Bayern,False,...,no,no_information,True,NaN,80807,1.0,81.0,False,München,May19
161,Bayern,district_heating,False,True,16,NaN,1959.0,True,Bayern,True,...,NaN,Corneliusstra&szlig;e,True,apartment,80469,2.0,76.7,True,München,Oct19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268688,Bayern,oil_heating,False,True,24,2240.00,NaN,True,Bayern,True,...,no,no_information,False,ground_floor,81247,3.0,118.0,True,München,Feb20
268712,Bayern,district_heating,False,True,11,1810.17,1980.0,False,Bayern,True,...,negotiable,St.-Cajetan-Str.,True,terraced_flat,81669,3.0,125.5,True,München,Oct19
268752,Bayern,central_heating,False,True,32,1290.00,1985.0,True,Bayern,True,...,no,Knorrstra&szlig;e,True,apartment,80807,1.0,167.1,False,München,May19
268818,Bayern,central_heating,False,True,9,1792.00,NaN,False,Bayern,True,...,negotiable,Stuckstra&szlig;e,True,NaN,81677,3.0,175.8,False,München,May19
268839,Bayern,district_heating,False,True,15,1980.00,1900.0,True,Bayern,False,...,no,no_information,False,ground_floor,80799,2.0,NaN,False,München,Sep18

In [14]:
df = df[df.baseRent.between(100,10000, inclusive=True)] #drop extreme rent values
df = df[df.livingSpace.between(10, 500, inclusive=True)] #drop extreme and wrongly coded values
df = df[df.noRooms.between(0,15, inclusive=True)] #drop extreme and probably wrongly coded value
df = df[np.isfinite(df['totalRent'])] #drop observations where totalRent isn't available
df = df[df.totalRent.between(100,10000, inclusive=True)] #drop extreme totalRent value
df

,regio1,heatingType,newlyConst,balcony,picturecount,totalRent,yearConstructed,hasKitchen,geo_bln,cellar,...,petsAllowed,street,lift,typeOfFlat,geo_plz,noRooms,thermalChar,garden,regio2,date
23,Bayern,central_heating,False,False,18,2030.00,1871.0,True,Bayern,True,...,no,no_information,False,apartment,80331,2.0,48.4,False,München,Oct19
28,Bayern,NaN,False,True,25,2400.00,1956.0,False,Bayern,False,...,NaN,Burgunderstra&szlig;e,True,NaN,80804,3.0,210.6,False,München,May19
32,Bayern,NaN,False,True,29,2780.00,2016.0,False,Bayern,False,...,NaN,Am Oberwiesenfeld,True,NaN,80809,3.0,44.8,False,München,Feb20
118,Bayern,NaN,True,True,14,1390.00,2018.0,False,Bayern,False,...,no,no_information,True,NaN,80807,1.0,81.0,False,München,May19
281,Bayern,central_heating,True,True,8,2010.00,2019.0,True,Bayern,True,...,no,Leonistra&szlig;e,True,maisonette,81476,1.5,35.2,False,München,Feb20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268688,Bayern,oil_heating,False,True,24,2240.00,NaN,True,Bayern,True,...,no,no_information,False,ground_floor,81247,3.0,118.0,True,München,Feb20
268712,Bayern,district_heating,False,True,11,1810.17,1980.0,False,Bayern,True,...,negotiable,St.-Cajetan-Str.,True,terraced_flat,81669,3.0,125.5,True,München,Oct19
268752,Bayern,central_heating,False,True,32,1290.00,1985.0,True,Bayern,True,...,no,Knorrstra&szlig;e,True,apartment,80807,1.0,167.1,False,München,May19
268818,Bayern,central_heating,False,True,9,1792.00,NaN,False,Bayern,True,...,negotiable,Stuckstra&szlig;e,True,NaN,81677,3.0,175.8,False,München,May19
268839,Bayern,district_heating,False,True,15,1980.00,1900.0,True,Bayern,False,...,no,no_information,False,ground_floor,80799,2.0,NaN,False,München,Sep18

In [16]:
df

,regio1,heatingType,newlyConst,balcony,picturecount,totalRent,yearConstructed,hasKitchen,geo_bln,cellar,...,petsAllowed,street,lift,typeOfFlat,geo_plz,noRooms,thermalChar,garden,regio2,date
23,Bayern,central_heating,False,False,18,2030.00,1871.0,True,Bayern,True,...,no,no_information,False,apartment,80331,2.0,48.4,False,München,Oct19
28,Bayern,NaN,False,True,25,2400.00,1956.0,False,Bayern,False,...,NaN,Burgunderstra&szlig;e,True,NaN,80804,3.0,210.6,False,München,May19
32,Bayern,NaN,False,True,29,2780.00,2016.0,False,Bayern,False,...,NaN,Am Oberwiesenfeld,True,NaN,80809,3.0,44.8,False,München,Feb20
118,Bayern,NaN,True,True,14,1390.00,2018.0,False,Bayern,False,...,no,no_information,True,NaN,80807,1.0,81.0,False,München,May19
281,Bayern,central_heating,True,True,8,2010.00,2019.0,True,Bayern,True,...,no,Leonistra&szlig;e,True,maisonette,81476,1.5,35.2,False,München,Feb20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268688,Bayern,oil_heating,False,True,24,2240.00,NaN,True,Bayern,True,...,no,no_information,False,ground_floor,81247,3.0,118.0,True,München,Feb20
268712,Bayern,district_heating,False,True,11,1810.17,1980.0,False,Bayern,True,...,negotiable,St.-Cajetan-Str.,True,terraced_flat,81669,3.0,125.5,True,München,Oct19
268752,Bayern,central_heating,False,True,32,1290.00,1985.0,True,Bayern,True,...,no,Knorrstra&szlig;e,True,apartment,80807,1.0,167.1,False,München,May19
268818,Bayern,central_heating,False,True,9,1792.00,NaN,False,Bayern,True,...,negotiable,Stuckstra&szlig;e,True,NaN,81677,3.0,175.8,False,München,May19
268839,Bayern,district_heating,False,True,15,1980.00,1900.0,True,Bayern,False,...,no,no_information,False,ground_floor,80799,2.0,NaN,False,München,Sep18

In [17]:
print(df)
df.to_csv('test1.csv') #convert files to csv

        regio1       heatingType  newlyConst  balcony  picturecount  \
23      Bayern   central_heating       False    False            18
28      Bayern               NaN       False     True            25
32      Bayern               NaN       False     True            29
118     Bayern               NaN        True     True            14
281     Bayern   central_heating        True     True             8
...        ...               ...         ...      ...           ...
268688  Bayern       oil_heating       False     True            24
268712  Bayern  district_heating       False     True            11
268752  Bayern   central_heating       False     True            32
268818  Bayern   central_heating       False     True             9
268839  Bayern  district_heating       False     True            15

        totalRent  yearConstructed  hasKitchen geo_bln  cellar  ...  \
23        2030.00           1871.0        True  Bayern    True  ...
28        2400.00           1956.0       False  Bayern   False  ...
32        2780.00           2016.0       False  Bayern   False  ...
118       1390.00           2018.0       False  Bayern   False  ...
281       2010.00           2019.0        True  Bayern    True  ...
...           ...              ...         ...     ...     ...  ...
268688    2240.00              NaN        True  Bayern    True  ...
268712    1810.17           1980.0       False  Bayern    True  ...
268752    1290.00           1985.0        True  Bayern    True  ...
268818    1792.00              NaN       False  Bayern    True  ...
268839    1980.00           1900.0        True  Bayern   False  ...

        petsAllowed                 street   lift     typeOfFlat geo_plz  \
23               no         no_information  False      apartment   80331
28              NaN  Burgunderstra&szlig;e   True            NaN   80804
32              NaN      Am Oberwiesenfeld   True            NaN   80809
118              no         no_information   True            NaN   80807
281              no      Leonistra&szlig;e   True     maisonette   81476
...             ...                    ...    ...            ...     ...
268688           no         no_information  False   ground_floor   81247
268712   negotiable       St.-Cajetan-Str.   True  terraced_flat   81669
268752           no      Knorrstra&szlig;e   True      apartment   80807
268818   negotiable      Stuckstra&szlig;e   True            NaN   81677
268839           no         no_information  False   ground_floor   80799

       noRooms thermalChar  garden   regio2   date
23         2.0        48.4   False  München  Oct19
28         3.0       210.6   False  München  May19
32         3.0        44.8   False  München  Feb20
118        1.0        81.0   False  München  May19
281        1.5        35.2   False  München  Feb20
...        ...         ...     ...      ...    ...
268688     3.0       118.0    True  München  Feb20
268712     3.0       125.5    True  München  Oct19
268752     1.0       167.1   False  München  May19
268818     3.0       175.8   False  München  May19
268839     2.0         NaN   False  München  Sep18

[3934 rows x 25 columns]